### ISSUE TITLE
Quick note on your commit messages.

### ISSUE THREAD

**Issue by adam-waldenberg** [ptibom/Kelde#2]
Hi everyone. I quickly looked at your repo today.

Try to have good commit messages when you create commits. Try to use git gui and structure your commits before you push. Try to help each other and keep your group mates in line.

For example;

https://github.com/ptibom/Kelde/commit/e34741021a3c6252e1ffa2f8729082aee04f5669

Is an example of a really bad commit that has a strange description and adds/modifies many unrelated fixes/files in the same commit.

Commit messages such as "..." are not acceptable either.

A good guideline to commit messages is to not only describe what you do, but also say something about why you do it.

If you feel that you want to improve the commit messages on your local branch, this is possible as long as you have not pushed to master. With "git rebase" you can split or squash your commits and rewrite commit messages.

Remember, someone will look at your workflow and your commits at the end of the course. Good comments make things easier for us and enable us to see how you have worked.

/Adam Waldenberg

**Comment by ptibom** [comment]
Thanks for the feedback. Unfortunately Hossein already merged his branch with master. But we will all think about this in the future.
