### ISSUE TITLE
Meeting, Week 21.

### ISSUE THREAD

**Issue by adam-waldenberg** [ptibom/Kelde#3]
Hi. Here's a status update (and reminder) for Thursday:

1. I expect you to show me your application with a few running use cases. Make sure everything compiles and runs. Again, it should compile from a terminal.
2. Clean up your RAD and include use cases, domain model, mockups and everything inside the RAD document itself.
3. Create a "completed" SDD with a UML analysis model showing the whole application.
4. Don't forget to look over your unit tests and how much of the model you are covering. If you have no tests it's high time to write them. Use jacoco to check your coverage.
5. Fix all PMD and FindBugs violations.
6. The presentation schedule is up on the course web site; please check it out and contact Joachim if you need to be moved for some reason.

**Comment by DanielDSCOlsson** [comment]
Hej Adam, jag har problem med en branch,

På gitinspector står det andras rader har försvunnit, så då kommer de bli
knas om jag mergar till master.

Hur skall man gå till väga då?

tack, mvh Daniel

2015-05-18 9:00 GMT+02:00 Adam Waldenberg <notifications@github.com>:

>  Hi. Here's a status update (and reminder) for Thursday:
>
>    1. I expect you to show me your application with a few running use
>    cases. Make sure everything compiles and runs. Again, it should compile
>    from a terminal.
>    2. Clean up your RAD and include use cases, domain model, mockups and
>    everything inside the RAD document itself.
>    3. Create a "completed" SDD with a UML analysis model showing the
>    whole application.
>    4. Don't forget to look over your unit tests and how much of the model
>    you are covering. If you have no tests it's high time to write them. Use
>    jacoco to check your coverage.
>    5. Fix all PMD and FindBugs violations.
>    6. The presentation schedule is up on the course web site; please
>    check it out and contact Joachim if you need to be moved for some reason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ptibom/Kelde/issues/3>.
>



-- 
Daniel Olsson

**Comment by adam-waldenberg** [comment]
Ägaren för rader ändras när du ändrar rader vid en merge. Helt normalt. Men det borde bara vara det som du har ändrat på. Är det mer så låter det galet.

Glöm inte --grading flaggan till gitinspector när du kör det. Det är först då den kollar rekursivt (i hela historiken) efter originalägaren till en rad.

/Adam

**Comment by ptibom** [comment]
Problemet var att Daniel vid något tillfälle råkade pulla ner master och arbeta direkt i den. Och istället för att pusha en ofärdig Master så copy-pastade han alla nya filer till en egen branch. Och nu tror gitinspector att han gjort allt.

Han har gjort en ny branch nu och kopierat sina egna filer endast och ska merga på rätt sätt. Men det gör tyvärr att hans githistorik inte kommer synas i gitinspector.

**Comment by adam-waldenberg** [comment]
Ja, då tappar den historiken. När en helt otrackad rad introduceras så letar git i det fallet hela vägen tillbaka efter originalupphovsmannen till samtliga rader ;). Vilket också kan bli fel.

Lösningen är att cherry picka commitsen från originalbranchen till den nya... Då bibehålls det mesta av historiken. Sedan är det bara att merga mot master

Så:

1. Skapa en ny branch B baserad på master.
2. Cherry picka ändringar från originalbranchen A in till den nya branchen B.
3. Merga in B till master.

/Adam

**Comment by ptibom** [comment]
Ah det låter smart! Men nu har han redan kopierat för hand. Vi får se om
han orkar göra om det. :)
Den 25 maj 2015 14:41 skrev "Adam Waldenberg" <notifications@github.com>:

**Comment by adam-waldenberg** [comment]
Jag rekommenderar att göra så. Att tappa historiken är inte bra och ser mystiskt ut när vi tittar på repot.

Måste också sägas att omn bara vill cherry picka delar av en commit (vilket kan hända om man gjort för stora commits) så går det också att fixa. Då kan man exempelvis köra git cherry-pick och sedan komplettera med en git reset -p för att ta bort det man inte vill ha.

/Adam

**Comment by ptibom** [comment]
Tack för tipsen Daniel ska försöka senare har han sagt.
Den 25 maj 2015 14:53 skrev "Adam Waldenberg" <notifications@github.com>:
