### ISSUE TITLE
Week 22, Last supervised meeting

### ISSUE THREAD

**Issue by adam-waldenberg** [ptibom/Kelde#4]
Hi everyone. Here is what I expect from you for Thursday;
1. Get as many use cases completed as you can.
2. Show me a somewhat "completed" version of your application.
3. Get the SDD and RAD into a somewhat final version. We can quickly go through them on Thursday.
4. As usual, fix everything reported by STAN, PMD and Findbugs.
5. This one is a new one; I have purposely avoided it until now because I know that the source code changes a lot during the end of the project: read up on sequence diagrams. Before you have completed the final version of the SDD, you should add a  sequence diagram over your main use case. An example of a good sequence diagram is here:
   http://agilemodeling.com/style/sequenceDiagram.htm
   If you think things will still change a lot; you can probably hold off before creating it.  We will have a chance to talk more about this on Thursday.
6. Clean up your project repository if needed. If there are any unused or unnecessary files; remove them. The same goes for unused classes and methods inside the code base.

**Comment by adam-waldenberg** [comment]
Just noticed a few things in your repo.

1. What's up with the untitled/ directory ?
2. .metadata, .idea folders should not be part of the project. You should add them to the gitignore file just to make sure they don't accidentally get committed again.

We have talked several times about using git gui to make sure no crud was commited with a push... Yes I'm looking at  you Daniel, as you are the culprit responsible :).

/Adam

**Comment by ptibom** [comment]
We already have gitignore to take care of that. I don't know why someone
added project folders but thanks for the heads up.
Den 27 maj 2015 16:09 skrev "Adam Waldenberg" <notifications@github.com>:

**Comment by DanielDSCOlsson** [comment]
Sorry yes, It's my merge just recently, I saw it was there was gonna remove
it in the next push :)

2015-05-27 16:09 GMT+02:00 Adam Waldenberg <notifications@github.com>:

>  Just noticed a few things in your repo.
>
>    1. What's up with the untitled/ directory ?
>    2. .metadata, .idea folders should not be part of the project. You
>    should add them to the gitignore file just to make sure they don't
>    accidentally get committed again.
>
> We have talked several times about using git gui to make sure no crud was
> commited with a push... Yes I'm looking at you Daniel, as you are the
> culprit responsible :).
>
> /Adam
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ptibom/Kelde/issues/4#issuecomment-105925410>.
>



-- 
Daniel Olsson
